apiVersion: apps/v1
kind: Deployment
metadata:
  name: treasure-ana
  namespace: treasure-hunt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: treasure-ana
  template:
    metadata:
      labels:
        app: treasure-ana
    spec:
      containers:
        - name: web
          image: ghcr.io/fredyunivalle/treasure-new:latest
          ports:
            - containerPort: 80
          env:
            - name: TITLE
              value: "Treasure Hunt — Fredy"
            - name: STUDENT
              value: "Fredy"
            - name: SALT
              value: "DS3univalle"
            - name: KEY_HASH
              value: "e03071406de634efb44ae42fb52a19523ac5646281b91de291133e2c37106da0"
            - name: CLUE
              valueFrom:
                secretKeyRef:
                  name: ana-clue
                  key: CLUE
---
apiVersion: v1
kind: Service
metadata:
  name: treasure-ana
  namespace: treasure-hunt
spec:
  selector:
    app: treasure-ana
  ports:
    - name: http
      port: 80
      targetPort: 80
      # nodePort: 31080   # (opcional) fija uno en el rango 30000–32767
  type: NodePort

